# Example kickit service

# bro think he adele
description = "hello"

# A non-optional service will crash the init system if it fails
optional = true

# Whether to show service's output on master init console or not
shout = true

#
# The service pattern (copy exactly - capitals & everything)
#
# Choose from:
# * Standard -> Runs in the background (init watches in the background),
# * RunOnce  -> Runs once, init waits for it to finish
#
pattern = "RunOnce"

#
# You may want to disable this if your service creates a very large log
# or already has an existing logfile to avoid duplicates
#
logger = true

#
# If the service you're using needs a run directory to be created
# (like dbus does), you can specify the settings for one here
#
#run_folder = { name = "hello", owner = 0, group = 0, mode = 0o755 }

# The path of the executable followed by the argument(s)
exec = ["/bin/bash", "-c", "echo 'Hello world' >&2"]

#
# Create a chroot container with new, unshared namespaces. This is optional
# but provides extra security
#
[sandbox]
flags = [
  "NewMount", "NewCGroup", "NewUts", "NewIpc", "NewUser", "NewPid", "NewNetwork"
]
import = [
  "/usr/bin/bash",
  "/usr/lib/libc.so.6", "/usr/lib/libreadline.so.8", "/usr/lib/libncursesw.so.6"
]
