# Example kickit target

# How verbosely we store logs
# 0 => Don't log anything (not recommended),
# 1 => Capture services log only,
# 2 => Capture services + init log (default)
log_level = 2

# Our device's hostname- defaults to "localhost" if unset
# (do not include spaces here)
hostname = "my_very_cool_computer"

# Our services that we will run- more about
# these will be defined in each of their configs
services = ["agetty", "polkit", "NetworkManager", "lightdm"]

# (debug builds only)- Store a copy of our
# runfs on the disk, for debugging
debug_dump = false
