# Example kickit target

# Our device's hostname- defaults to "localhost" if unset
# (do not include spaces here)
hostname = "my_very_cool_computer"

# Our services that we will run- more about
# these will be defined in each of their configs
services = ["agetty", "polkit", "NetworkManager", "lightdm"]

# (debug builds only)- Store a copy of our
# runfs on the disk, for debugging
debug_dump = false
