name: Build release

on: [push, workflow_dispatch]

jobs:
  release:
    if: (${{ github.event_name == 'push' }} && contains(github.event.head_commit.message, '(build)')) || true
    name: Build release
    uses: ./.github/workflows/build.yml
    with:
      inputs:
        release: true
